// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njdggavilwpujimlwsnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qZGdnYXZpbHdwdWppbWx3c253Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NTg1NzEsImV4cCI6MjA2NDIzNDU3MX0.M7tyJ7bOVOuxHD4vnaYCX6sJWlH0T_QsE7GQH2YR3rU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);